{
 "title": "Centrifuge Validator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_cpu_usage_percentage" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_memory_usage_bytes" }
   ]
  },
  {
   "title": "Block height",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "substrate_block_height_number{status=\"best\"}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "substrate_block_height_number{status=\"best\"}"
    }
   ]
  },
  {
   "title": "Block height target",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "substrate_block_height_number{status=\"sync_target\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "substrate_peers_count" }
   ]
  },
  {
   "title": "Traffic IN",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "substrate_network_per_sec_bytes{direction=\"download\"}"
    }
   ]
  },
  {
   "title": "Traffic OUT",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "substrate_network_per_sec_bytes{direction=\"upload\"}"
    }
   ]
  },
  {
   "title": "Block height finalized",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height_number{status=\"finalized\"}[5m])"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_peers_count" }
   ]
  },
  {
   "title": "Ready TX",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number"
    }
   ]
  }
 ]
}